# OSIsoft Academic Hub Python Library

**For updated Deschutes dataset and new asset interface**

## To install Academic Hub Python library

In [1]:
!pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple ocs-academic-hub==0.71.0

Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Requirement already satisfied: ocs-academic-hub==0.71.0 in /opt/conda/lib/python3.7/site-packages (0.71.0)
Requirement already satisfied: typeguard>=2.4.1 in /opt/conda/lib/python3.7/site-packages (from ocs-academic-hub==0.71.0) (2.9.1)
Requirement already satisfied: python-dateutil>=2.8.0 in /opt/conda/lib/python3.7/site-packages (from ocs-academic-hub==0.71.0) (2.8.1)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from ocs-academic-hub==0.71.0) (1.19.0)
Requirement already satisfied: ocs-sample-library-preview>=0.1.9rc0 in /opt/conda/lib/python3.7/site-packages (from ocs-academic-hub==0.71.0) (0.1.9rc0)
Requirement already satisfied: pandas>=0.24.2 in /opt/conda/lib/python3.7/site-packages (from ocs-academic-hub==0.71.0) (1.0.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil>=2.8.0->ocs-academic-hub==0.71.0) (1.15.0)
Requirement already satisfied: requests==2.23.0 in /opt/conda/lib/python3.7/site-packages (from ocs-sample-library-preview>=0.1.9rc0->ocs-academic-hub==0.71.0) (2.23.0)
Requirement already satisfied: pytz>=2017.2 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24.2->ocs-academic-hub==0.71.0) (2020.1)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests==2.23.0->ocs-sample-library-preview>=0.1.9rc0->ocs-academic-hub==0.71.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests==2.23.0->ocs-sample-library-preview>=0.1.9rc0->ocs-academic-hub==0.71.0) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests==2.23.0->ocs-sample-library-preview>=0.1.9rc0->ocs-academic-hub==0.71.0) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.7/site-packages (from requests==2.23.0->ocs-sample-library-preview>=0.1.9rc0->ocs-academic-hub==0.71.0) (3.0.4)

In [2]:
# It's sometimes necessary to uninstall previous versions, uncomment and run the following line. Then restart kernel and reinstall with previous cell
# !pip uninstall -y ocs-academic-hub ocs-sample-library-preview

## Import HubClient, necessary to connect and interact with OCS

In [3]:
from ocs_academic_hub import HubClient

## Running the following cell initiate the login sequence

Return to this web page when done

In [4]:
hub = HubClient()

env: OCS_HUB_CONFIG=config.ini
> configuration file: config.ini

## Get list of published hub datasets

NOTE: currently only `Deschutes-v2` supports the new interface. This notebook is specifically about this dataset.

In [5]:
hub.datasets()

['Deschutes', 'UCDavis.Facilities', 'Deschutes-v2']

## Get list of assets with Data Views

In [6]:
hub.assets()

['BB11',
 'BB12',
 'BB13',
 'BB14',
 'BB15',
 'C2_BBL1',
 'C2_FT1',
 'C2_PS1',
 'C2_PS2',
 'FV31',
 'FV32',
 'FV33',
 'FV34',
 'FV35',
 'FV36']

## Display current active dataset

NOTE: it will be possible to switch it once other dataset supports the new asset interface.

In [7]:
hub.current_dataset()

'Deschutes-v2'

## List of all Data Views

In [8]:
hub.asset_dataviews()

['hubdv_v2-all_columns-bb11',
 'hubdv_v2-all_columns-bb12',
 'hubdv_v2-all_columns-bb13',
 'hubdv_v2-all_columns-bb14',
 'hubdv_v2-all_columns-bb15',
 'hubdv_v2-all_columns-c2_bbl1',
 'hubdv_v2-all_columns-c2_ft1',
 'hubdv_v2-all_columns-c2_ps1',
 'hubdv_v2-all_columns-c2_ps2',
 'hubdv_v2-all_columns-fv31',
 'hubdv_v2-all_columns-fv32',
 'hubdv_v2-all_columns-fv33',
 'hubdv_v2-all_columns-fv34',
 'hubdv_v2-all_columns-fv35',
 'hubdv_v2-all_columns-fv36',
 'hubdv_v2-adf_prediction-fv31',
 'hubdv_v2-adf_prediction-fv32',
 'hubdv_v2-adf_prediction-fv33',
 'hubdv_v2-adf_prediction-fv34',
 'hubdv_v2-adf_prediction-fv35',
 'hubdv_v2-adf_prediction-fv36',
 'hubdv_v2-cooling_prediction-fv31',
 'hubdv_v2-cooling_prediction-fv32',
 'hubdv_v2-cooling_prediction-fv33',
 'hubdv_v2-cooling_prediction-fv34',
 'hubdv_v2-cooling_prediction-fv35',
 'hubdv_v2-cooling_prediction-fv36',
 'hubdv_v2-pca-fv31',
 'hubdv_v2-pca-fv32',
 'hubdv_v2-pca-fv33',
 'hubdv_v2-pca-fv34',
 'hubdv_v2-pca-fv35',
 'hubdv_v2-pca-fv36']

## List of Data Views exclusive to Fermenter Vessel #31 (FV31)

In [9]:
hub.asset_dataviews(asset="FV31")

['hubdv_v2-all_columns-fv31',
 'hubdv_v2-adf_prediction-fv31',
 'hubdv_v2-cooling_prediction-fv31',
 'hubdv_v2-pca-fv31']

## Get the OCS namespace associate to the dataset

In [10]:
namespace_id = hub.namespace_of("Deschutes-v2")
namespace_id

'academic_hub_01'

## Get Data View structure

With Stream Name, the column name under which stream data appears, its value type and engineering units if available

In [11]:
hub.dataview_definition(namespace_id, "hubdv_v2-all_columns-fv31")

,OCS_StreamName,DV_Column,Value_Type,EngUnits
0,B2_CL_C2_FV31/ADF,ADF,Float,
1,B2_CL_C2_FV31/BRAND.CV,Brand,Category,
2,B2_CL_C2_FV31/DcrsFvFullPlato,FV Full Plato,Float,Plato
3,B2_CL_C2_FV31/Diacetyl,Diacetyl,Integer,ppb
4,B2_CL_C2_FV31/EndPhaseTime.CV,End Phase Time,Float,m
5,B2_CL_C2_FV31/Fermentation_Start_Time,Fermentation Start Time,Timestamp,
6,B2_CL_C2_FV31/Integrator Key,Integrator Key,Float,
7,B2_CL_C2_FV31/Phase Duration,Phase Duration,Integer,
8,B2_CL_C2_FV31/Plato,Plato,Float,Plato
9,B2_CL_C2_FV31/Predicted Transition,Predicted Transition,String,
10,B2_CL_C2_FV31/Prediction.Deviation,Deviation,Float,
11,B2_CL_C2_FV31/STATUS.CV,Status,Category,
12,B2_CL_C2_FV31/VesselID,VesselID,Integer,
13,B2_CL_C2_FV31/VesselProcedure,Vessel Procedure,String,
14,B2_CL_C2_FV31/YEAST.CV,Yeast Strain,Category,
15,B2_CL_C2_FV31/YEASTGEN.CV,Yeast Generation,Integer,
16,B2_CL_C2_FV31/YeastOutTotalizer,Yeast Out Totalizer,Float,
17,B2_CL_C2_FV31_FQ1360_A/TOTAL.CV,Volume In,Float,bbl
18,B2_CL_C2_FV31_FQ1360_B/TOTAL.CV,Volume Out,Float,bbl
19,B2_CL_C2_FV31_LT1360/PV.CV,Volume,Float,bbl
20,B2_CL_C2_FV31_PIC1362/OUT.CV,PIC OUT,Float,%
21,B2_CL_C2_FV31_PIC1362/PV.CV,PIC PV,Float,psi
22,B2_CL_C2_FV31_PIC1362/SP.CV,PIC SP,Float,psi
23,B2_CL_C2_FV31_TIC1360A/OUT.CV,Bottom TIC OUT,Float,%
24,B2_CL_C2_FV31_TIC1360A/PV.CV,Bottom TIC PV,Float,Â°F
25,B2_CL_C2_FV31_TIC1360A/SP.CV,Bottom TIC SP,Float,Â°F
26,B2_CL_C2_FV31_TIC1360B/PV.CV,Middle TIC PV,Float,Â°F
27,B2_CL_C2_FV31_TIC1360B/SP.CV,Middle TIC SP,Float,Â°F
28,B2_CL_C2_FV31_TIC1360C/OUT.CV,Top TIC OUT,Float,%
29,B2_CL_C2_FV31_TIC1360C/PV.CV,Top TIC PV,Float,Â°F
30,B2_CL_C2_FV31_TIC1360C/SP.CV,Top TIC SP,Float,Â°F

## Getting data from a Data View

Between start and end date, with interpolation interval (format is HH:MM:SS)

In [12]:
df_fv31 = hub.dataview_interpolated_pd(namespace_id, "hubdv_v2-all_columns-fv31", "2017-02-01", "2017-08-01", "00:10:00")
df_fv31

  ==> Finished 'dataview_interpolated_pd' in       7.2144 secs [ 3.61K rows/sec ]

,Timestamp,Asset_Id,ADF,FV Full Plato,Diacetyl,End Phase Time,Fermentation Start Time,Integrator Key,Phase Duration,Plato,...,Bottom TIC PV,Bottom TIC SP,Middle TIC PV,Middle TIC SP,Top TIC OUT,Top TIC PV,Top TIC SP,Brand,Status,Yeast Strain
0,2017-02-01 00:00:00,FV31,0.719046,17.084625,70.0,NaN,2017-01-26T07:30:03.2369995Z,-1.0,NaN,4.8,...,52.903126,30.00000,53.798340,30.00000,100.0,53.674717,30.00000,Inversion,Cooling,NCYC1187
1,2017-02-01 00:10:00,FV31,0.719046,17.084625,70.0,NaN,2017-01-26T07:30:03.2369995Z,-1.0,NaN,4.8,...,52.470764,30.00000,53.607800,30.00000,100.0,53.494137,30.00000,Inversion,Cooling,NCYC1187
2,2017-02-01 00:20:00,FV31,0.719046,17.084625,70.0,NaN,2017-01-26T07:30:03.2369995Z,-1.0,NaN,4.8,...,53.044888,30.00000,53.483322,30.00000,100.0,53.200000,30.00000,Inversion,Cooling,NCYC1187
3,2017-02-01 00:30:00,FV31,0.719046,17.084625,70.0,NaN,2017-01-26T07:30:03.2369995Z,-1.0,NaN,4.8,...,52.353100,30.00000,53.009580,30.00000,100.0,52.928270,30.00000,Inversion,Cooling,NCYC1187
4,2017-02-01 00:40:00,FV31,0.719046,17.084625,70.0,NaN,2017-01-26T07:30:03.2369995Z,-1.0,NaN,4.8,...,51.935390,30.00000,52.899998,30.00000,100.0,52.800003,30.00000,Inversion,Cooling,NCYC1187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26060,2017-07-31 23:20:00,FV31,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,...,120.469670,120.46967,121.074780,121.07478,0.0,122.412380,122.41238,None,Blown Down,NCYC1187
26061,2017-07-31 23:30:00,FV31,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,...,146.111760,146.11176,146.489960,146.48996,0.0,146.404880,146.40488,None,Blown Down,NCYC1187
26062,2017-07-31 23:40:00,FV31,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,...,148.456530,148.45653,148.685960,148.68596,0.0,148.372310,148.37231,None,Blown Down,NCYC1187
26063,2017-07-31 23:50:00,FV31,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,...,149.000000,149.00000,149.179180,149.17918,0.0,148.868840,148.86884,None,Blown Down,NCYC1187
26064,2017-08-01 00:00:00,FV31,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,...,140.839600,140.83960,141.100000,141.10000,0.0,140.732010,140.73201,None,Clean,None

In [13]:
df_fv31.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26065 entries, 0 to 26064
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Timestamp                26065 non-null  datetime64[ns]
 1   Asset_Id                 26065 non-null  object
 2   ADF                      14672 non-null  float64
 3   FV Full Plato            21851 non-null  float64
 4   Diacetyl                 17153 non-null  float64
 5   End Phase Time           0 non-null      float64
 6   Fermentation Start Time  21220 non-null  object
 7   Integrator Key           25759 non-null  float64
 8   Phase Duration           0 non-null      float64
 9   Plato                    14672 non-null  float64
 10  Predicted Transition     0 non-null      float64
 11  Deviation                0 non-null      float64
 12  VesselID                 26065 non-null  int64
 13  Vessel Procedure         0 non-null      float64
 14  Yeast Generation         26064 non-null  float64
 15  Yeast Out Totalizer      0 non-null      float64
 16  Volume In                26056 non-null  float64
 17  Volume Out               26056 non-null  float64
 18  Volume                   26056 non-null  float64
 19  PIC OUT                  26056 non-null  float64
 20  PIC PV                   26056 non-null  float64
 21  PIC SP                   26056 non-null  float64
 22  Bottom TIC OUT           26056 non-null  float64
 23  Bottom TIC PV            26056 non-null  float64
 24  Bottom TIC SP            26056 non-null  float64
 25  Middle TIC PV            26056 non-null  float64
 26  Middle TIC SP            26056 non-null  float64
 27  Top TIC OUT              26056 non-null  float64
 28  Top TIC PV               26056 non-null  float64
 29  Top TIC SP               26056 non-null  float64
 30  Brand                    26065 non-null  object
 31  Status                   26065 non-null  object
 32  Yeast Strain             26065 non-null  object
dtypes: datetime64[ns](1), float64(26), int64(1), object(5)
memory usage: 6.6+ MB

## Data Views with multiple assets

Some Data Views return data for fermenter vessels 31 up to 36. Cell below is how to get their names.

In [14]:
hub.asset_dataviews(single=False)

['hubdv_v2-all_columns-fv31-36',
 'hubdv_v2-adf_prediction-fv31-36',
 'hubdv_v2-cooling_prediction-fv31-36',
 'hubdv_v2-pca-fv31-36']

## Get result

The column "Asset_Id" indicates which asset the data row belongs to. The data order is all data for FV31 in increasing time, followed by FV32 and so on up to FV36.

In [15]:
df_fv31_36 = hub.dataview_interpolated_pd(namespace_id, "hubdv_v2-adf_prediction-fv31-36", "2017-02-01", "2017-08-01", "00:10:00")
df_fv31_36

  ==> Finished 'dataview_interpolated_pd' in       3.0561 secs [ 51.17K rows/sec ]

,Timestamp,Asset_Id,ADF,FV Full Plato,Fermentation Start Time,Plato,Brand,Status
0,2017-02-01 00:00:00,FV31,0.719046,17.084625,2017-01-26T07:30:03.2369995Z,4.80000,Inversion,Cooling
1,2017-02-01 00:10:00,FV31,0.719046,17.084625,2017-01-26T07:30:03.2369995Z,4.80000,Inversion,Cooling
2,2017-02-01 00:20:00,FV31,0.719046,17.084625,2017-01-26T07:30:03.2369995Z,4.80000,Inversion,Cooling
3,2017-02-01 00:30:00,FV31,0.719046,17.084625,2017-01-26T07:30:03.2369995Z,4.80000,Inversion,Cooling
4,2017-02-01 00:40:00,FV31,0.719046,17.084625,2017-01-26T07:30:03.2369995Z,4.80000,Inversion,Cooling
...,...,...,...,...,...,...,...,...
156385,2017-07-31 23:20:00,FV36,0.787345,17.026010,2017-07-25T00:43:17.1560056Z,3.62067,Inversion,Cooling
156386,2017-07-31 23:30:00,FV36,0.787345,17.026010,2017-07-25T00:43:17.1560056Z,3.62067,Inversion,Cooling
156387,2017-07-31 23:40:00,FV36,0.787345,17.026010,2017-07-25T00:43:17.1560056Z,3.62067,Inversion,Cooling
156388,2017-07-31 23:50:00,FV36,0.787345,17.026010,2017-07-25T00:43:17.1560056Z,3.62067,Inversion,Cooling
156389,2017-08-01 00:00:00,FV36,0.787345,17.026010,2017-07-25T00:43:17.1560056Z,3.62067,Inversion,Cooling